Repository DeepanshuGOYAL05/Statistics_R_Codes, pull requests merged in 2023-10, with the labels that each got.

#11 Update logistics_code.R
  logistics_code.R
Labels: hacktoberfest accpeted

#10 Update Anova.R
  Anova.R
Labels: hacktoberfest accpeted

#21 Create BarChart.R
  BarChart.R
Labels: help wanted, hacktoberfest 2023, hacktoberfest accpeted

#24 Create piechart.R
  piechart.R
Labels: help wanted, hacktoberfest 2023, hacktoberfest accpeted

#23 Create scatterplot.R
  scatterplot.R
Labels: help wanted, hacktoberfest 2023, hacktoberfest accpeted

#36 Create Wilcoxon_Signed-Rank_Test.R
  Wilcoxon_Signed-Rank_Test.R
Labels: hacktoberfest 2023, hacktoberfest accpeted

#35 Create friedman_test.R
  friedman_test.R
Labels: hacktoberfest 2023, hacktoberfest accpeted

#34 Create Kruskal_walis_test.R
  Kruskal_walis_test.R
Labels: hacktoberfest 2023, hacktoberfest accpeted

#41 Update Kruskal_walis_test.R
  Kruskal_walis_test.R
Labels: hacktoberfest 2023, hacktoberfest accpeted

#40 Update friedman_test.R
  friedman_test.R
Labels: help wanted, hacktoberfest 2023, hacktoberfest accpeted

#39 Update Wilcoxon_Signed-Rank_Test.R
  Wilcoxon_Signed-Rank_Test.R
Labels: hacktoberfest 2023, hacktoberfest accpeted

#38 Update Mann-Whitney_U-Test.R
  Mann-Whitney_U-Test.R
Labels: hacktoberfest 2023, hacktoberfest accpeted
